<testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="48.389" timestamp="2024-02-24T14:48:46.194537" hostname="wmytych"><testcase classname="test_esp_helper_utils.pytest_esp_helper_utils" name="test_esp_helper_utils" time="48.294"><failure message="pexpect.exceptions.TIMEOUT: Not found &quot;never coming&quot;&#10;Bytes in current buffer (color code eliminated): ... I (4639) esp_https_ota: Writing to partition subtype 16 at offset 0x110000 1970-01-01 00:00:04 | INFO | ota_c_validate_image:91 | Running firmware version:... (total 229488 bytes)&#10;Please check the full log here: /tmp/pytest-embedded/2024-02-24_13-48-46-220199/test_esp_helper_utils/dut.log">self = &lt;pytest_embedded_idf.dut.IdfDut object at 0x7f8c4f669950&gt;, pattern = 'never coming', expect_all = False
not_matching = (), args = (), kwargs = {}, patterns = ['never coming'], res = []
debug_str = 'Not found "never coming"\nBytes in current buffer (color code eliminated): ... I (4639) esp_https_ota: Writing to par... bytes)\nPlease check the full log here: /tmp/pytest-embedded/2024-02-24_13-48-46-220199/test_esp_helper_utils/dut.log'

    @functools.wraps(func)  # noqa
    def wrapper(
        self, pattern, *args, expect_all: bool = False, not_matching: List[Union[str, re.Pattern]] = (), **kwargs
    ) -&gt; Union[Union[Match, AnyStr], List[Union[Match, AnyStr]]]:
        patterns = to_list(pattern)
        res = []
        while patterns:
            try:
&gt;               index = func(self, pattern, *args, **kwargs)  # noqa

/home/wmytych/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/pytest_embedded/dut.py:76: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/wmytych/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/pytest_embedded/dut.py:131: in expect
    return self.pexpect_proc.expect(pattern, **kwargs)
/home/wmytych/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/pexpect/spawnbase.py:354: in expect
    return self.expect_list(compiled_pattern_list,
/home/wmytych/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/pexpect/spawnbase.py:383: in expect_list
    return exp.expect_loop(timeout)
/home/wmytych/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/pexpect/expect.py:181: in expect_loop
    return self.timeout(e)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;pexpect.expect.Expecter object at 0x7f8c4f8c1150&gt;
err = TIMEOUT("&lt;pytest_embedded.log.PexpectProcess object at 0x7f8c4f835d90&gt;\nsearcher: searcher_re:\n    0: re.compile(b'never coming')")

    def timeout(self, err=None):
        spawn = self.spawn
    
        spawn.before = spawn._before.getvalue()
        spawn.after = TIMEOUT
        index = self.searcher.timeout_index
        if index &gt;= 0:
            spawn.match = TIMEOUT
            spawn.match_index = index
            return index
        else:
            spawn.match = None
            spawn.match_index = None
            msg = str(spawn)
            msg += '\nsearcher: %s' % self.searcher
            if err is not None:
                msg = str(err) + '\n' + msg
    
            exc = TIMEOUT(msg)
            exc.__cause__ = None    # in Python 3.x we can use "raise exc from None"
&gt;           raise exc
E           pexpect.exceptions.TIMEOUT: &lt;pytest_embedded.log.PexpectProcess object at 0x7f8c4f835d90&gt;
E           searcher: searcher_re:
E               0: re.compile(b'never coming')
E           &lt;pytest_embedded.log.PexpectProcess object at 0x7f8c4f835d90&gt;
E           searcher: searcher_re:
E               0: re.compile(b'never coming')

/home/wmytych/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/pexpect/expect.py:144: TIMEOUT

The above exception was the direct cause of the following exception:

dut = &lt;pytest_embedded_idf.dut.IdfDut object at 0x7f8c4f669950&gt;

    @pytest.mark.esp32
    def test_esp_helper_utils(dut):
        # expect from what esptool.py printed to sys.stdout
        dut.expect('TESTING ESP HELPER UTILS')
        dut.expect('Starting OTA')
&gt;       dut.expect('never coming')

pytest_esp_helper_utils.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;pytest_embedded_idf.dut.IdfDut object at 0x7f8c4f669950&gt;, pattern = 'never coming', expect_all = False
not_matching = (), args = (), kwargs = {}, patterns = ['never coming'], res = []
debug_str = 'Not found "never coming"\nBytes in current buffer (color code eliminated): ... I (4639) esp_https_ota: Writing to par... bytes)\nPlease check the full log here: /tmp/pytest-embedded/2024-02-24_13-48-46-220199/test_esp_helper_utils/dut.log'

    @functools.wraps(func)  # noqa
    def wrapper(
        self, pattern, *args, expect_all: bool = False, not_matching: List[Union[str, re.Pattern]] = (), **kwargs
    ) -&gt; Union[Union[Match, AnyStr], List[Union[Match, AnyStr]]]:
        patterns = to_list(pattern)
        res = []
        while patterns:
            try:
                index = func(self, pattern, *args, **kwargs)  # noqa
            except (pexpect.EOF, pexpect.TIMEOUT) as e:
                debug_str = (
                    f'Not found "{str(pattern)}"\n'
                    f'Bytes in current buffer (color code eliminated): {self.pexpect_proc.buffer_debug_str}\n'
                    f'Please check the full log here: {self.logfile}'
                )
&gt;               raise e.__class__(debug_str) from e
E               pexpect.exceptions.TIMEOUT: Not found "never coming"
E               Bytes in current buffer (color code eliminated): ... I (4639) esp_https_ota: Writing to partition subtype 16 at offset 0x110000 1970-01-01 00:00:04 | INFO | ota_c_validate_image:91 | Running firmware version:... (total 229488 bytes)
E               Please check the full log here: /tmp/pytest-embedded/2024-02-24_13-48-46-220199/test_esp_helper_utils/dut.log

/home/wmytych/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/pytest_embedded/dut.py:83: TIMEOUT</failure></testcase></testsuite></testsuites>